services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tasks
    ports:
      - "5432:5432"
    volumes:
      - task_pg_data:/bitnami/postgresql

volumes:
  task_pg_data: